include $(JLM_ROOT)/tests/libjlm/ir/operators/Makefile.sub

TESTS += \
	libjlm/ir/test-aggregation \
	libjlm/ir/test-cfg \
	libjlm/ir/test-cfg-node \
	libjlm/ir/test-cfg-orderings \
	libjlm/ir/test-cfg-prune \
	libjlm/ir/test-cfg-purge \
	libjlm/ir/test-cfg-validity \
	libjlm/ir/test-domtree \
	libjlm/ir/test-ssa-destruction \
	libjlm/ir/TestAnnotation \
