include tests/libjlm/ir/operators/Makefile.sub

TESTS += \
	libjlm/ir/test-cfg \
	libjlm/ir/test-cfg-node \
	libjlm/ir/test-cfg-orderings \
	libjlm/ir/test-cfg-prune \
	libjlm/ir/test-cfg-validity \
	libjlm/ir/test-domtree
