TESTS += \
    jlm/util/test-disjointset \
    jlm/util/test-file \
    jlm/util/test-intrusive-hash \
    jlm/util/test-intrusive-list \
    jlm/util/TestBiMap \
    jlm/util/TestHashSet \
    jlm/util/TestMath \
    jlm/util/TestStatistics \
