# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

libllvm_SOURCES = \
    jlm/llvm/DotWriter.cpp \
    jlm/llvm/TestRvsdgs.cpp \
    \
    jlm/llvm/backend/IpGraphToLlvmConverter.cpp \
    jlm/llvm/backend/RvsdgToIpGraphConverter.cpp \
    \
    jlm/llvm/frontend/ControlFlowRestructuring.cpp \
    jlm/llvm/frontend/InterProceduralGraphConversion.cpp \
    jlm/llvm/frontend/LlvmModuleConversion.cpp \
    \
    jlm/llvm/ir/aggregation.cpp \
    jlm/llvm/ir/Annotation.cpp \
    jlm/llvm/ir/attribute.cpp \
    jlm/llvm/ir/basic-block.cpp \
    jlm/llvm/ir/CallingConvention.cpp \
    jlm/llvm/ir/CallSummary.cpp \
    jlm/llvm/ir/cfg.cpp \
    jlm/llvm/ir/cfg-structure.cpp \
    jlm/llvm/ir/cfg-node.cpp \
    jlm/llvm/ir/domtree.cpp \
    jlm/llvm/ir/ipgraph.cpp \
    jlm/llvm/ir/ipgraph-module.cpp \
    jlm/llvm/ir/LambdaMemoryState.cpp \
    jlm/llvm/ir/Linkage.cpp \
    jlm/llvm/ir/TypeConverter.cpp \
    jlm/llvm/ir/operators/AggregateOperations.cpp \
    jlm/llvm/ir/operators/alloca.cpp \
    jlm/llvm/ir/operators/call.cpp \
    jlm/llvm/ir/operators/delta.cpp \
    jlm/llvm/ir/operators/FunctionPointer.cpp \
    jlm/llvm/ir/operators/GetElementPtr.cpp \
    jlm/llvm/ir/operators/IntegerOperations.cpp \
    jlm/llvm/ir/operators/IOBarrier.cpp \
    jlm/llvm/ir/operators/lambda.cpp \
    jlm/llvm/ir/operators/Load.cpp \
    jlm/llvm/ir/operators/MemoryStateOperations.cpp \
    jlm/llvm/ir/operators/operators.cpp \
    jlm/llvm/ir/operators/sext.cpp \
    jlm/llvm/ir/operators/SpecializedArithmeticIntrinsicOperations.cpp \
    jlm/llvm/ir/operators/StdLibIntrinsicOperations.cpp \
    jlm/llvm/ir/operators/Store.cpp \
    jlm/llvm/ir/print.cpp \
    jlm/llvm/ir/RvsdgModule.cpp \
    jlm/llvm/ir/ssa.cpp \
    jlm/llvm/ir/tac.cpp \
    jlm/llvm/ir/Trace.cpp \
    jlm/llvm/ir/types.cpp \
    jlm/llvm/ir/variable.cpp \
    \
    jlm/llvm/opt/alias-analyses/AliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysisPrecisionEvaluator.cpp \
    jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.cpp \
    jlm/llvm/opt/alias-analyses/Andersen.cpp \
    jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp \
    jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysisStateEncoder.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraph.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.cpp \
    jlm/llvm/opt/AggregateAllocaSplitting.cpp \
    jlm/llvm/opt/CommonNodeElimination.cpp \
    jlm/llvm/opt/DeadNodeElimination.cpp \
    jlm/llvm/opt/IfConversion.cpp \
    jlm/llvm/opt/inlining.cpp \
    jlm/llvm/opt/InvariantValueRedirection.cpp \
    jlm/llvm/opt/LoadChainSeparation.cpp \
    jlm/llvm/opt/LoopStrengthReduction.cpp \
    jlm/llvm/opt/LoopUnswitching.cpp \
    jlm/llvm/opt/PredicateCorrelation.cpp \
    jlm/llvm/opt/pull.cpp \
    jlm/llvm/opt/push.cpp \
    jlm/llvm/opt/reduction.cpp \
    jlm/llvm/opt/RvsdgTreePrinter.cpp \
    jlm/llvm/opt/ScalarEvolution.cpp \
    jlm/llvm/opt/StoreValueForwarding.cpp \
    jlm/llvm/opt/unroll.cpp \

libllvm_HEADERS = \
    jlm/llvm/DotWriter.hpp \
    jlm/llvm/TestRvsdgs.hpp \
    \
    jlm/llvm/backend/IpGraphToLlvmConverter.hpp \
    jlm/llvm/backend/RvsdgToIpGraphConverter.hpp \
    \
    jlm/llvm/opt/unroll.hpp \
    jlm/llvm/opt/DeadNodeElimination.hpp \
    jlm/llvm/opt/inlining.hpp \
    jlm/llvm/opt/CommonNodeElimination.hpp \
    jlm/llvm/opt/push.hpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysisPrecisionEvaluator.hpp \
    jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/Andersen.hpp \
    jlm/llvm/opt/alias-analyses/DifferencePropagation.hpp \
    jlm/llvm/opt/alias-analyses/EliminatedModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/LazyCycleDetection.hpp \
    jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysisStateEncoder.hpp \
    jlm/llvm/opt/alias-analyses/ModRefEliminator.hpp \
    jlm/llvm/opt/alias-analyses/MemoryStateEncoder.hpp \
    jlm/llvm/opt/alias-analyses/ModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/ModRefSummary.hpp \
    jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp \
    jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/PointsToGraph.hpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.hpp \
    jlm/llvm/opt/AggregateAllocaSplitting.hpp \
    jlm/llvm/opt/pull.hpp \
    jlm/llvm/opt/reduction.hpp \
    jlm/llvm/opt/IfConversion.hpp \
    jlm/llvm/opt/InvariantValueRedirection.hpp \
    jlm/llvm/opt/LoadChainSeparation.hpp \
    jlm/llvm/opt/LoopStrengthReduction.hpp \
    jlm/llvm/opt/LoopUnswitching.hpp \
    jlm/llvm/opt/PredicateCorrelation.hpp \
    jlm/llvm/opt/RvsdgTreePrinter.hpp \
    jlm/llvm/opt/ScalarEvolution.hpp \
    jlm/llvm/opt/StoreValueForwarding.hpp \
    jlm/llvm/frontend/LlvmModuleConversion.hpp \
    jlm/llvm/frontend/ControlFlowRestructuring.hpp \
    jlm/llvm/frontend/InterProceduralGraphConversion.hpp \
    jlm/llvm/ir/ipgraph-module.hpp \
    jlm/llvm/ir/RvsdgModule.hpp \
    jlm/llvm/ir/Linkage.hpp \
    jlm/llvm/ir/Annotation.hpp \
    jlm/llvm/ir/attribute.hpp \
    jlm/llvm/ir/CallingConvention.hpp \
    jlm/llvm/ir/CallSummary.hpp \
    jlm/llvm/ir/LambdaMemoryState.hpp \
    jlm/llvm/ir/tac.hpp \
    jlm/llvm/ir/domtree.hpp \
    jlm/llvm/ir/cfg-node.hpp \
    jlm/llvm/ir/ipgraph.hpp \
    jlm/llvm/ir/cfg.hpp \
    jlm/llvm/ir/ssa.hpp \
    jlm/llvm/ir/TypeConverter.hpp \
    jlm/llvm/ir/variable.hpp \
    jlm/llvm/ir/basic-block.hpp \
    jlm/llvm/ir/print.hpp \
    jlm/llvm/ir/Trace.hpp \
    jlm/llvm/ir/types.hpp \
    jlm/llvm/ir/cfg-structure.hpp \
    jlm/llvm/ir/operators/AggregateOperations.hpp \
    jlm/llvm/ir/operators/operators.hpp \
    jlm/llvm/ir/operators/Load.hpp \
    jlm/llvm/ir/operators/MemoryStateOperations.hpp \
    jlm/llvm/ir/operators/FunctionPointer.hpp \
    jlm/llvm/ir/operators/GetElementPtr.hpp \
    jlm/llvm/ir/operators/IntegerOperations.hpp \
    jlm/llvm/ir/operators/IOBarrier.hpp \
    jlm/llvm/ir/operators/delta.hpp \
    jlm/llvm/ir/operators/Store.hpp \
    jlm/llvm/ir/operators/alloca.hpp \
    jlm/llvm/ir/operators/call.hpp \
    jlm/llvm/ir/operators/sext.hpp \
    jlm/llvm/ir/operators/lambda.hpp \
    jlm/llvm/ir/operators/SpecializedArithmeticIntrinsicOperations.hpp \
    jlm/llvm/ir/operators/StdLibIntrinsicOperations.hpp \
    jlm/llvm/ir/aggregation.hpp \

$(eval $(call common_library,libllvm))

run-libllvm-tests_SOURCES = \
    jlm/llvm/DotWriterTests.cpp \
    \
    jlm/llvm/backend/CastingTests.cpp \
    jlm/llvm/backend/IpGraphToLlvmConverterTests.cpp \
    jlm/llvm/backend/RvsdgToIpGraphConverterTests.cpp \
    \
    jlm/llvm/frontend/AttributeConversionTests.cpp \
    jlm/llvm/frontend/CastingTests.cpp \
    jlm/llvm/frontend/ControlFlowRestructuringTests.cpp \
    jlm/llvm/frontend/EndlessLoopTests.cpp \
    jlm/llvm/frontend/ExportTests.cpp \
    jlm/llvm/frontend/FNegTests.cpp \
    jlm/llvm/frontend/FunctionCallTests.cpp \
    jlm/llvm/frontend/LlvmModuleConversionTests.cpp \
    jlm/llvm/frontend/LlvmPhiConversionTests.cpp \
    jlm/llvm/frontend/LoadTests.cpp \
    jlm/llvm/frontend/RecursiveDataTests.cpp \
    jlm/llvm/frontend/SelectTests.cpp \
    jlm/llvm/frontend/SpecializedArithmeticIntrinsicOperationTests.cpp \
    jlm/llvm/frontend/StoreTests.cpp \
    jlm/llvm/frontend/ThreeAddressCodeConversionTests.cpp \
    \
    jlm/llvm/ir/operators/CallTests.cpp \
    jlm/llvm/ir/operators/ConstantFPTests.cpp \
    jlm/llvm/ir/operators/DeltaTests.cpp \
    jlm/llvm/ir/operators/FreeTests.cpp \
    jlm/llvm/ir/operators/GetElementPtrTests.cpp \
    jlm/llvm/ir/operators/LambdaTests.cpp \
    jlm/llvm/ir/operators/LoadTests.cpp \
    jlm/llvm/ir/operators/MemoryStateOperationTests.cpp \
    jlm/llvm/ir/operators/PhiTests.cpp \
    jlm/llvm/ir/operators/SExtTests.cpp \
    jlm/llvm/ir/operators/StdLibIntrinsicOperationsTests.cpp \
    jlm/llvm/ir/operators/StoreTests.cpp \
    \
    jlm/llvm/ir/AggregationTests.cpp \
    jlm/llvm/ir/AnnotationTests.cpp \
    jlm/llvm/ir/AttributeSetTests.cpp \
    jlm/llvm/ir/CallSummaryTests.cpp \
    jlm/llvm/ir/CfgNodeTests.cpp \
    jlm/llvm/ir/CfgOrderingsTests.cpp \
    jlm/llvm/ir/CfgPruneTests.cpp \
    jlm/llvm/ir/CfgPurgeTests.cpp \
    jlm/llvm/ir/CfgStructureTests.cpp \
    jlm/llvm/ir/CfgTests.cpp \
    jlm/llvm/ir/CfgValidityTests.cpp \
    jlm/llvm/ir/DomTreeTests.cpp \
    jlm/llvm/ir/SsaDestructionTests.cpp \
    jlm/llvm/ir/ThreeAddressCodeTests.cpp \
    jlm/llvm/ir/TraceTests.cpp \
    jlm/llvm/ir/TypeConverterTests.cpp \
    jlm/llvm/ir/TypeTests.cpp \
    \
    jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizerTests.cpp \
    jlm/llvm/opt/alias-analyses/AndersenTests.cpp \
    jlm/llvm/opt/alias-analyses/DifferencePropagationTests.cpp \
    jlm/llvm/opt/alias-analyses/LazyCycleDetectionTests.cpp \
    jlm/llvm/opt/alias-analyses/LocalAliasAnalysisTests.cpp \
    jlm/llvm/opt/alias-analyses/MemoryStateEncoderTests.cpp \
    jlm/llvm/opt/alias-analyses/PointerObjectSetTests.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysisTests.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphTests.cpp \
    jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizerTests.cpp \
    \
    jlm/llvm/opt/AggregateAllocaSplittingTests.cpp \
    jlm/llvm/opt/CommonNodeEliminationTests.cpp \
    jlm/llvm/opt/DeadNodeEliminationTests.cpp \
    jlm/llvm/opt/IfConversionTests.cpp \
    jlm/llvm/opt/InliningTests.cpp \
    jlm/llvm/opt/InvariantValueRedirectionTests.cpp \
    jlm/llvm/opt/LoadChainSeparationTests.cpp \
    jlm/llvm/opt/LoopStrengthReductionTests.cpp \
    jlm/llvm/opt/LoopUnswitchingTests.cpp \
    jlm/llvm/opt/NodeReductionTests.cpp \
    jlm/llvm/opt/PredicateCorrelationTests.cpp \
    jlm/llvm/opt/PullTests.cpp \
    jlm/llvm/opt/PushTests.cpp \
    jlm/llvm/opt/RvsdgTreePrinterTests.cpp \
    jlm/llvm/opt/ScalarEvolutionTests.cpp \
    jlm/llvm/opt/StoreValueForwardingTests.cpp \
    jlm/llvm/opt/UnrollTests.cpp \

run-libllvm-tests_LIBS = libllvm librvsdg libutil
run-libllvm-tests_EXTRA_LDFLAGS = $(shell $(LLVMCONFIG) --ldflags --libs --system-libs)
$(eval $(call common_test,run-libllvm-tests))
