# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

libllvm_SOURCES = \
    jlm/llvm/DotWriter.cpp \
    jlm/llvm/TestRvsdgs.cpp \
    \
    jlm/llvm/backend/IpGraphToLlvmConverter.cpp \
    jlm/llvm/backend/RvsdgToIpGraphConverter.cpp \
    \
    jlm/llvm/frontend/ControlFlowRestructuring.cpp \
    jlm/llvm/frontend/InterProceduralGraphConversion.cpp \
    jlm/llvm/frontend/LlvmInstructionConversion.cpp \
    jlm/llvm/frontend/LlvmModuleConversion.cpp \
    \
    jlm/llvm/ir/aggregation.cpp \
    jlm/llvm/ir/Annotation.cpp \
    jlm/llvm/ir/attribute.cpp \
    jlm/llvm/ir/basic-block.cpp \
    jlm/llvm/ir/CallSummary.cpp \
    jlm/llvm/ir/cfg.cpp \
    jlm/llvm/ir/cfg-structure.cpp \
    jlm/llvm/ir/cfg-node.cpp \
    jlm/llvm/ir/domtree.cpp \
    jlm/llvm/ir/ipgraph.cpp \
    jlm/llvm/ir/ipgraph-module.cpp \
    jlm/llvm/ir/LambdaMemoryState.cpp \
    jlm/llvm/ir/Linkage.cpp \
    jlm/llvm/ir/TypeConverter.cpp \
    jlm/llvm/ir/operators/alloca.cpp \
    jlm/llvm/ir/operators/call.cpp \
    jlm/llvm/ir/operators/delta.cpp \
    jlm/llvm/ir/operators/FunctionPointer.cpp \
    jlm/llvm/ir/operators/GetElementPtr.cpp \
    jlm/llvm/ir/operators/IntegerOperations.cpp \
    jlm/llvm/ir/operators/IOBarrier.cpp \
    jlm/llvm/ir/operators/lambda.cpp \
    jlm/llvm/ir/operators/Load.cpp \
    jlm/llvm/ir/operators/MemCpy.cpp \
    jlm/llvm/ir/operators/MemoryStateOperations.cpp \
    jlm/llvm/ir/operators/operators.cpp \
    jlm/llvm/ir/operators/sext.cpp \
    jlm/llvm/ir/operators/SpecializedArithmeticIntrinsicOperations.cpp \
    jlm/llvm/ir/operators/Store.cpp \
    jlm/llvm/ir/print.cpp \
    jlm/llvm/ir/RvsdgModule.cpp \
    jlm/llvm/ir/ssa.cpp \
    jlm/llvm/ir/tac.cpp \
    jlm/llvm/ir/Trace.cpp \
    jlm/llvm/ir/types.cpp \
    jlm/llvm/ir/variable.cpp \
    \
    jlm/llvm/opt/alias-analyses/AliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysisPrecisionEvaluator.cpp \
    jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.cpp \
    jlm/llvm/opt/alias-analyses/Andersen.cpp \
    jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp \
    jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysisStateEncoder.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraph.cpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.cpp \
    jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.cpp \
    jlm/llvm/opt/CommonNodeElimination.cpp \
    jlm/llvm/opt/DeadNodeElimination.cpp \
    jlm/llvm/opt/IfConversion.cpp \
    jlm/llvm/opt/inlining.cpp \
    jlm/llvm/opt/InvariantValueRedirection.cpp \
    jlm/llvm/opt/LoadChainSeparation.cpp \
    jlm/llvm/opt/LoopUnswitching.cpp \
    jlm/llvm/opt/PredicateCorrelation.cpp \
    jlm/llvm/opt/pull.cpp \
    jlm/llvm/opt/push.cpp \
    jlm/llvm/opt/reduction.cpp \
    jlm/llvm/opt/RvsdgTreePrinter.cpp \
    jlm/llvm/opt/ScalarEvolution.cpp \
    jlm/llvm/opt/unroll.cpp \

libllvm_HEADERS = \
    jlm/llvm/DotWriter.hpp \
    jlm/llvm/TestRvsdgs.hpp \
    \
    jlm/llvm/backend/IpGraphToLlvmConverter.hpp \
    jlm/llvm/backend/RvsdgToIpGraphConverter.hpp \
    \
    jlm/llvm/opt/unroll.hpp \
    jlm/llvm/opt/DeadNodeElimination.hpp \
    jlm/llvm/opt/inlining.hpp \
    jlm/llvm/opt/CommonNodeElimination.hpp \
    jlm/llvm/opt/push.hpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/AliasAnalysisPrecisionEvaluator.hpp \
    jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/Andersen.hpp \
    jlm/llvm/opt/alias-analyses/DifferencePropagation.hpp \
    jlm/llvm/opt/alias-analyses/EliminatedModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/LazyCycleDetection.hpp \
    jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysisStateEncoder.hpp \
    jlm/llvm/opt/alias-analyses/ModRefEliminator.hpp \
    jlm/llvm/opt/alias-analyses/MemoryStateEncoder.hpp \
    jlm/llvm/opt/alias-analyses/ModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/ModRefSummary.hpp \
    jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp \
    jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.hpp \
    jlm/llvm/opt/alias-analyses/PointsToAnalysis.hpp \
    jlm/llvm/opt/alias-analyses/PointsToGraph.hpp \
    jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.hpp \
    jlm/llvm/opt/pull.hpp \
    jlm/llvm/opt/reduction.hpp \
    jlm/llvm/opt/IfConversion.hpp \
    jlm/llvm/opt/InvariantValueRedirection.hpp \
    jlm/llvm/opt/LoadChainSeparation.hpp \
    jlm/llvm/opt/LoopUnswitching.hpp \
    jlm/llvm/opt/PredicateCorrelation.hpp \
    jlm/llvm/opt/RvsdgTreePrinter.hpp \
    jlm/llvm/opt/ScalarEvolution.hpp \
    jlm/llvm/frontend/LlvmModuleConversion.hpp \
    jlm/llvm/frontend/ControlFlowRestructuring.hpp \
    jlm/llvm/frontend/LlvmConversionContext.hpp \
    jlm/llvm/frontend/LlvmInstructionConversion.hpp \
    jlm/llvm/frontend/InterProceduralGraphConversion.hpp \
    jlm/llvm/ir/operators.hpp \
    jlm/llvm/ir/ipgraph-module.hpp \
    jlm/llvm/ir/RvsdgModule.hpp \
    jlm/llvm/ir/Linkage.hpp \
    jlm/llvm/ir/Annotation.hpp \
    jlm/llvm/ir/attribute.hpp \
    jlm/llvm/ir/CallSummary.hpp \
    jlm/llvm/ir/LambdaMemoryState.hpp \
    jlm/llvm/ir/tac.hpp \
    jlm/llvm/ir/domtree.hpp \
    jlm/llvm/ir/cfg-node.hpp \
    jlm/llvm/ir/ipgraph.hpp \
    jlm/llvm/ir/cfg.hpp \
    jlm/llvm/ir/ssa.hpp \
    jlm/llvm/ir/TypeConverter.hpp \
    jlm/llvm/ir/variable.hpp \
    jlm/llvm/ir/basic-block.hpp \
    jlm/llvm/ir/print.hpp \
    jlm/llvm/ir/Trace.hpp \
    jlm/llvm/ir/types.hpp \
    jlm/llvm/ir/cfg-structure.hpp \
    jlm/llvm/ir/operators/operators.hpp \
    jlm/llvm/ir/operators/Load.hpp \
    jlm/llvm/ir/operators/MemCpy.hpp \
    jlm/llvm/ir/operators/MemoryStateOperations.hpp \
    jlm/llvm/ir/operators/FunctionPointer.hpp \
    jlm/llvm/ir/operators/GetElementPtr.hpp \
    jlm/llvm/ir/operators/IntegerOperations.hpp \
    jlm/llvm/ir/operators/IOBarrier.hpp \
    jlm/llvm/ir/operators/delta.hpp \
    jlm/llvm/ir/operators/Store.hpp \
    jlm/llvm/ir/operators/alloca.hpp \
    jlm/llvm/ir/operators/call.hpp \
    jlm/llvm/ir/operators/sext.hpp \
    jlm/llvm/ir/operators/lambda.hpp \
    jlm/llvm/ir/operators/SpecializedArithmeticIntrinsicOperations.hpp \
    jlm/llvm/ir/aggregation.hpp \

libllvm_TESTS += \
    tests/jlm/llvm/opt/LoopUnswitchingTests \
    tests/jlm/llvm/opt/NodeReductionTests \
    tests/jlm/llvm/opt/PredicateCorrelationTests \
    tests/jlm/llvm/opt/RvsdgTreePrinterTests \
    tests/jlm/llvm/opt/ScalarEvolutionTests \
    tests/jlm/llvm/opt/test-inlining \
    tests/jlm/llvm/opt/test-pull \
    tests/jlm/llvm/opt/test-push \
    tests/jlm/llvm/opt/test-unroll \

libllvm_TEST_LIBS = \
    libjlmtest \
    libllvm \
    librvsdg \
    libutil \

libllvm_TEST_EXTRA_LDFLAGS = $(shell $(LLVMCONFIG) --ldflags --libs --system-libs)

$(eval $(call common_library,libllvm))

tests/jlm/llvm/run-libllvm-tests_SOURCES = \
    tests/jlm/llvm/DotWriterTests.cpp \
    \
    tests/jlm/llvm/backend/IpGraphToLlvmConverterTests.cpp \
    tests/jlm/llvm/backend/RvsdgToIpGraphConverterTests.cpp \
    \
    tests/jlm/llvm/frontend/llvm/ControlFlowRestructuringTests.cpp \
    tests/jlm/llvm/frontend/llvm/LoadTests.cpp \
    tests/jlm/llvm/frontend/llvm/MemCpyTests.cpp \
    tests/jlm/llvm/frontend/llvm/SpecializedArithmeticIntrinsicOperationTests.cpp \
    tests/jlm/llvm/frontend/llvm/StoreTests.cpp \
    tests/jlm/llvm/frontend/llvm/TestAttributeConversion.cpp \
    tests/jlm/llvm/frontend/llvm/test-endless-loop.cpp \
    tests/jlm/llvm/frontend/llvm/test-export.cpp \
    tests/jlm/llvm/frontend/llvm/TestFNeg.cpp \
    tests/jlm/llvm/frontend/llvm/test-function-call.cpp \
    tests/jlm/llvm/frontend/llvm/LlvmPhiConversionTests.cpp \
    tests/jlm/llvm/frontend/llvm/test-recursive-data.cpp \
    tests/jlm/llvm/frontend/llvm/test-select.cpp \
    tests/jlm/llvm/frontend/llvm/ThreeAddressCodeConversionTests.cpp \
    \
    tests/jlm/llvm/ir/operators/LoadTests.cpp \
    tests/jlm/llvm/ir/operators/MemCpyTests.cpp \
    tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp \
    tests/jlm/llvm/ir/operators/TestCall.cpp \
    tests/jlm/llvm/ir/operators/test-ConstantFP.cpp \
    tests/jlm/llvm/ir/operators/test-delta.cpp \
    tests/jlm/llvm/ir/operators/TestFree.cpp \
    tests/jlm/llvm/ir/operators/TestGetElementPtr.cpp \
    tests/jlm/llvm/ir/operators/TestLambda.cpp \
    tests/jlm/llvm/ir/operators/TestPhi.cpp \
    tests/jlm/llvm/ir/operators/test-sext.cpp \
    tests/jlm/llvm/ir/operators/StoreTests.cpp \
    \
    tests/jlm/llvm/ir/AttributeSetTests.cpp \
    tests/jlm/llvm/ir/test-aggregation.cpp \
    tests/jlm/llvm/ir/test-cfg.cpp \
    tests/jlm/llvm/ir/test-cfg-node.cpp \
    tests/jlm/llvm/ir/test-cfg-orderings.cpp \
    tests/jlm/llvm/ir/test-cfg-prune.cpp \
    tests/jlm/llvm/ir/test-cfg-purge.cpp \
    tests/jlm/llvm/ir/test-cfg-structure.cpp \
    tests/jlm/llvm/ir/test-cfg-validity.cpp \
    tests/jlm/llvm/ir/test-domtree.cpp \
    tests/jlm/llvm/ir/test-ssa-destruction.cpp \
    tests/jlm/llvm/ir/TestTypes.cpp \
    tests/jlm/llvm/ir/TestAnnotation.cpp \
    tests/jlm/llvm/ir/TestCallSummary.cpp \
    tests/jlm/llvm/ir/ThreeAddressCodeTests.cpp \
    tests/jlm/llvm/ir/TraceTests.cpp \
    tests/jlm/llvm/ir/TypeConverterTests.cpp \
    \
    tests/jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizerTests.cpp \
    tests/jlm/llvm/opt/alias-analyses/LocalAliasAnalysisTests.cpp \
    tests/jlm/llvm/opt/alias-analyses/PointsToGraphTests.cpp \
    tests/jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysisTests.cpp \
    tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp \
    tests/jlm/llvm/opt/alias-analyses/TestDifferencePropagation.cpp \
    tests/jlm/llvm/opt/alias-analyses/TestLazyCycleDetection.cpp \
    tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp \
    tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp \
    tests/jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizerTests.cpp \
    \
    tests/jlm/llvm/opt/CommonNodeEliminationTests.cpp \
    tests/jlm/llvm/opt/DeadNodeEliminationTests.cpp \
    tests/jlm/llvm/opt/IfConversionTests.cpp \
    tests/jlm/llvm/opt/InvariantValueRedirectionTests.cpp \
    tests/jlm/llvm/opt/LoadChainSeparationTests.cpp \


tests/jlm/llvm/run-libllvm-tests_LIBS = libllvm librvsdg libutil
tests/jlm/llvm/run-libllvm-tests_EXTRA_LDFLAGS = $(shell $(LLVMCONFIG) --ldflags --libs --system-libs)
$(eval $(call common_test,tests/jlm/llvm/run-libllvm-tests))
