TESTS += \
	libjlm/test-bitops \
	libjlm/test-call \
	libjlm/test-constant \
	libjlm/test-dowhile \
	libjlm/test-fibrec \
	libjlm/test-getelementptr \
	libjlm/test-loadstore \
	libjlm/test-trunc \
	libjlm/test-undefvalue \
	libjlm/test-linear \
	libjlm/test-ifthen \
	libjlm/test-phi \
	libjlm/test-switch \
	libjlm/test-switch_fallthrough \
	libjlm/test-unreachable \
	libjlm/test-while \
