include tests/libjlm/backend/Makefile.sub
include tests/libjlm/frontend/Makefile.sub
include tests/libjlm/ir/Makefile.sub
include tests/libjlm/opt/Makefile.sub

TESTS += \
	libjlm/test-cfg-structure \
	libjlm/test-load \
	libjlm/test-restructuring \
	libjlm/test-sext \
	libjlm/test-store \
