# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

LIBJLM_SRC = \
    libjlm/src/backend/hls/rvsdg2rhls/add-triggers.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/gamma-conv.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/theta-conv.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/add-sinks.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/add-forks.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/check-rhls.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/rhls-dne.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/remove-unused-state.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/rvsdg2rhls.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/add-prints.cpp \
    libjlm/src/backend/hls/rvsdg2rhls/add-buffers.cpp \
    \
    libjlm/src/backend/hls/rhls2firrtl/base-hls.cpp \
    libjlm/src/backend/hls/rhls2firrtl/dot-hls.cpp \
    libjlm/src/backend/hls/rhls2firrtl/verilator-harness-hls.cpp \
    libjlm/src/backend/hls/rhls2firrtl/firrtl-hls.cpp \
    libjlm/src/backend/hls/rhls2firrtl/mlirgen.cpp \
    \
    libjlm/src/ir/hls/hls.cpp \

# Default verilator for Ubuntu 22.04
VERILATOR_BIN ?= verilator_bin
VERILATOR_PATH ?= /usr/share/verilator

FIRTOOL ?= $(CIRCT_PATH)/bin/firtool

.PHONY: libjlm-debug
libjlm-debug: CXXFLAGS += $(CXXFLAGS_DEBUG)
libjlm-debug: $(JLM_BUILD)/libjlm.a

.PHONY: libjlm-release
libjlm-release: CXXFLAGS += -O3
libjlm-release: $(JLM_BUILD)/libjlm.a

$(JLM_BUILD)/libjlm.a: CPPFLAGS += -I$(JLM_ROOT) -I$(shell $(LLVMCONFIG) --includedir) -I$(JLM_ROOT)/libjlm/include
$(JLM_BUILD)/libjlm.a: $(patsubst %.cpp, $(JLM_BUILD)/%.la, $(LIBJLM_SRC))

.PHONY: libjlm-clean
libjlm-clean:
	@rm -rf $(JLM_BUILD)/libjlm
	@rm -rf $(JLM_BUILD)/libjlm.a
