include $(JLM_ROOT)/tests/libjive/rvsdg/traverser/Makefile.sub

TESTS+=\
	libjive/rvsdg/test-binary \
	libjive/rvsdg/test-cse \
	libjive/rvsdg/test-gamma \
	libjive/rvsdg/test-graph \
	libjive/rvsdg/test-nodes \
	libjive/rvsdg/test-regionmismatch \
	libjive/rvsdg/test-statemux \
	libjive/rvsdg/test-theta \
	libjive/rvsdg/test-typemismatch \
