TESTS += \
    libjlm/frontend/llvm/TestAttributeConversion \
	libjlm/frontend/llvm/test-endless-loop \
	libjlm/frontend/llvm/test-function-call \
	libjlm/frontend/llvm/test-select \

include tests/libjlm/frontend/llvm/jlm-rvsdg/Makefile.sub
