name: "Restore jlm"
description: "Restores cached version of jlm."

runs:
  using: "composite"
  steps:
    - name: "Restore build"
      id: restore-jlm-build
      uses: actions/cache@v5
      with:
        path: |
          ${{ github.workspace }}/build-release
        key: ${{ runner.os }}-jlm-build-${{ github.sha }}

    - name: "Add build symlink"
      run: ln -s ${{ github.workspace }}/build-release ${{ github.workspace }}/build
      shell: bash

    - name: "Add executables to PATH"
      run: echo '${{ github.workspace }}/build' >> $GITHUB_PATH
      shell: bash
