name: "Install packages"
description: "Installs packages that the jlm framework depends on."

inputs:
  llvm-version:
    description: "LLVM/MLIR version that is installed"
    default: 18
    required: false

  install-llvm:
    description: "Install LLVM package. Default is 'false'."
    default: "false"
    required: false

  install-clang:
    description: "Install clang package. Default is 'false'."
    default: "false"
    required: false

  install-mlir:
    description: "Install MLIR packages. Default is 'false'."
    default: "false"
    required: false

  install-clang-format:
    description: "Install clang-format package. Default is 'false'."
    default: "false"
    required: false

  install-clang-tidy:
    description: "Install clang-tidy package. Default is 'false'."
    default: "false"
    required: false

  install-ninja:
    description: "Install ninja package. Default is 'false'."
    default: "false"
    required: false

  install-doxygen:
    description: "Install doxygen package. Default is 'false'."
    default: "false"
    required: false

  install-valgrind:
    description: "Install valgrind package. Default is 'false'."
    default: "false"
    required: false

  install-verilator:
    description: "Install verilator package. Default is 'false'."
    default: "false"
    required: false

  install-gtest:
    descrption: "Install gtest package. Default is 'false'."
    default: "false"
    required: false

  install-benchmark-deps:
    description: "Install dependencies necessary for compiling benchmarks. Default is 'false'."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Get LLVM apt key"
      if: ${{inputs.install-llvm == 'true'
        || inputs.install-clang == 'true'
        || inputs.install-mlir == 'true'
        || inputs.install-clang-format == 'true'
        || inputs.install-clang-tidy == 'true'}}
      run: |
        export HAS_LLVM_REPOSITORY=$(find /etc/apt/ -name *.list | xargs cat | grep llvm-toolchain-jammy-${{inputs.llvm-version}})
        if [[ -z $HAS_LLVM_REPOSITORY ]]; then
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository --no-update deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{inputs.llvm-version}} main
        fi
      shell: bash

    - name: "Update apt sources"
      run: sudo apt-get update
      shell: bash

    - name: "Install LLVM package"
      if: ${{inputs.install-llvm == 'true'}}
      run: |
        sudo apt-get install llvm-${{inputs.llvm-version}}-dev
        pip install "lit~=${{inputs.llvm-version}}.0"
        pip show lit
      shell: bash

    - name: "Install clang package"
      if: ${{inputs.install-clang == 'true'}}
      run: sudo apt-get install clang-${{inputs.llvm-version}}
      shell: bash

    - name: "Install MLIR packages"
      if: ${{inputs.install-mlir == 'true'}}
      run: |
        sudo apt-get install libmlir-${{inputs.llvm-version}}-dev mlir-${{inputs.llvm-version}}-tools
        if ! [ -f /usr/lib/x86_64-linux-gnu/libMLIR.so ]; then
          sudo ln -s /usr/lib/llvm-${{inputs.llvm-version}}/lib/libMLIR.so.${{inputs.llvm-version}}* /usr/lib/x86_64-linux-gnu/
          sudo ln -s /usr/lib/llvm-${{inputs.llvm-version}}/lib/libMLIR.so.${{inputs.llvm-version}}* /usr/lib/x86_64-linux-gnu/libMLIR.so
        fi
      shell: bash

    - name: "Install clang-format package"
      if: ${{inputs.install-clang-format == 'true'}}
      run: sudo apt-get install clang-format-${{inputs.llvm-version}}
      shell: bash

    - name: "Install clang-tidy package"
      if: ${{inputs.install-clang-tidy == 'true'}}
      run: sudo apt-get install clang-tidy-${{inputs.llvm-version}}
      shell: bash

    - name: "Install ninja package"
      if: ${{inputs.install-ninja == 'true'}}
      run: sudo apt-get install ninja-build
      shell: bash

    - name: "Install doxygen package"
      if: ${{inputs.install-doxygen == 'true'}}
      run: sudo apt-get install graphviz doxygen
      shell: bash

    - name: "Install valgrind package"
      if: ${{inputs.install-valgrind == 'true'}}
      run: sudo apt-get install valgrind
      shell: bash

    - name: "Install verilator package"
      if: ${{inputs.install-verilator == 'true'}}
      run: sudo apt-get install verilator
      shell: bash

    - name: "Install gtest package"
      if: ${{inputs.install-gtest == 'true'}}
      run: sudo apt-get install libgtest-dev
      shell: bash

    - name: "Update"
      if: ${{inputs.install-benchmark-deps == 'true'}}
      run: |
        sudo apt-get update
      shell: bash

    - name: "Search"
      if: ${{inputs.install-benchmark-deps == 'true'}}
      run: |
        sudo apt-cache search just
      shell: bash

    - name: "Just"
      if: ${{inputs.install-benchmark-deps == 'true'}}
      run: |
        sudo apt-get install just
      shell: bash

    - name: "Install benchmark dependencies"
      if: ${{inputs.install-benchmark-deps == 'true'}}
      run: |
        sudo apt-get install \
        build-essential gcc-multilib gcc-mingw-w64 libasound2-dev libpulse-dev libdbus-1-dev \
        libfontconfig-dev libfreetype-dev libgnutls28-dev libgl-dev libunwind-dev \
        libx11-dev libxcomposite-dev libxcursor-dev libxfixes-dev libxi-dev libxrandr-dev \
        libxrender-dev libxext-dev libwayland-bin libwayland-dev libegl-dev \
        libxkbcommon-dev libxkbregistry-dev \
        libxaw7-dev xaw3dg-dev libgtk-3-dev libglib2.0-dev libtree-sitter-dev \
        libgif-dev libxpm-dev libjpeg-dev libtiff-dev libgnutls28-dev \
        libmpfr-dev libxxhash-dev gawk flex bison bear just
      shell: bash
