name: "Install packages"
description: "Installs packages that the jlm framework depends on."

inputs:
  install-llvm:
    description: "Install LLVM package. Default is 'false'."
    default: "false"
    required: false

  install-clang:
    description: "Install clang package. Default is 'false'."
    default: "false"
    required: false

  install-mlir:
    description: "Install MLIR packages. Default is 'false'."
    default: "false"
    required: false

  install-clang-format:
    description: "Install clang-format package. Default is 'false'."
    default: "false"
    required: false

  install-ninja:
    description: "Install ninja package. Default is 'false'."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Get LLVM apt key and update apt sources"
      if: ${{inputs.install-llvm == 'true'
        || inputs.install-clang == 'true'
        || inputs.install-mlir == 'true'
        || inputs.install-clang-format == 'true'}}
      run: |
        export HAS_LLVM_REPOSITORY=$(find /etc/apt/ -name *.list | xargs cat | grep llvm-toolchain-jammy-16)
        echo $HAS_LLVM_REPOSITORY
        if [[ -z HAS_LLVM_REPOSITORY ]]; then
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main
        fi
      shell: bash

    - name: "Install LLVM package"
      if: ${{inputs.install-llvm == 'true'}}
      run: |
        sudo apt-get install llvm-16-dev
        pip install lit
      shell: bash

    - name: "Install clang package"
      if: ${{inputs.install-clang == 'true'}}
      run: sudo apt-get install clang-16
      shell: bash

    - name: "Install MLIR packages"
      if: ${{inputs.install-mlir == 'true'}}
      run: |
        sudo apt-get install libmlir-16-dev mlir-16-tools
        if ! [ -f /usr/lib/x86_64-linux-gnu/libMLIR.so ]; then
          sudo ln -s /usr/lib/llvm-16/lib/libMLIR.so.16 /usr/lib/x86_64-linux-gnu/
          sudo ln -s /usr/lib/llvm-16/lib/libMLIR.so.16 /usr/lib/x86_64-linux-gnu/libMLIR.so
        fi
      shell: bash

    - name: "Install clang-format package"
      if: ${{inputs.install-clang-format == 'true'}}
      run: sudo apt-get install clang-format-16
      shell: bash

    - name: "Install ninja package"
      if: ${{inputs.install-ninja == 'true'}}
      run: sudo apt-get install ninja-build
      shell: bash