include tests/libjlm/opt/alias-analyses/Makefile.sub

TESTS += \
	libjlm/opt/test-cne \
	libjlm/opt/TestDeadNodeElimination \
	libjlm/opt/test-inlining \
	libjlm/opt/test-invariance \
	libjlm/opt/test-inversion \
	libjlm/opt/TestLoadMuxReduction \
	libjlm/opt/test-pull \
	libjlm/opt/test-push \
	libjlm/opt/test-unroll \
