# Copyright 2022 Magnus Sjalander <work@sjalander.com>
# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

jlm-hls_SOURCES = \
	tools/jlm-hls/jlm-hls.cpp \

jlm-hls_LIBS = \
	libtooling \
	libhls \
	libllvm \
	librvsdg \
	libutil \

jlm-hls_EXTRA_LDFLAGS = \
    ${CIRCT_LDFLAGS} \
    $(shell $(LLVMCONFIG) --libs core irReader --ldflags --system-libs) \

$(eval $(call common_executable,jlm-hls))
