# Copyright 2022 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.


.PHONY: jlm-docs-build
jlm-docs-build:
	doxygen doxygen.conf

.PHONY: jlm-docs-clean
jlm-docs-clean:
	rm -rf $(JLM_ROOT)/docs/html
