# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

libhls_SOURCES = \
    jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.cpp \
    \
    jlm/hls/backend/rhls2firrtl/base-hls.cpp \
    jlm/hls/backend/rhls2firrtl/dot-hls.cpp \
    jlm/hls/backend/rhls2firrtl/json-hls.cpp \
    jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp \
    jlm/hls/backend/rhls2firrtl/verilator-harness-hls.cpp \
    jlm/hls/backend/rhls2firrtl/VerilatorHarnessAxi.cpp \
    \
    jlm/hls/backend/rvsdg2rhls/add-buffers.cpp \
    jlm/hls/backend/rvsdg2rhls/add-forks.cpp \
    jlm/hls/backend/rvsdg2rhls/add-prints.cpp \
    jlm/hls/backend/rvsdg2rhls/add-sinks.cpp \
    jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/check-rhls.cpp \
    jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.cpp \
    jlm/hls/backend/rvsdg2rhls/decouple-mem-state.cpp \
    jlm/hls/backend/rvsdg2rhls/distribute-constants.cpp \
    jlm/hls/backend/rvsdg2rhls/GammaConversion.cpp \
    jlm/hls/backend/rvsdg2rhls/hls-function-util.cpp \
    jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-queue.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-sep.cpp \
    jlm/hls/backend/rvsdg2rhls/memstate-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp \
    jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp \
    jlm/hls/backend/rvsdg2rhls/rhls-dne.cpp \
    jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp \
    jlm/hls/backend/rvsdg2rhls/stream-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/ThetaConversion.cpp \
    jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp \
    \
    jlm/hls/ir/hls.cpp \
    \
    jlm/hls/opt/cne.cpp \
    jlm/hls/opt/IOBarrierRemoval.cpp \
    jlm/hls/opt/IOStateElimination.cpp \
    \
    jlm/hls/util/view.cpp \
    \
    jlm/hls/HlsDotWriter.cpp \

libhls_HEADERS = \
    jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.hpp \
    \
    jlm/hls/backend/rhls2firrtl/base-hls.hpp \
    jlm/hls/backend/rhls2firrtl/dot-hls.hpp \
    jlm/hls/backend/rhls2firrtl/json-hls.hpp \
    jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp \
    jlm/hls/backend/rhls2firrtl/verilator-harness-hls.hpp \
    jlm/hls/backend/rhls2firrtl/VerilatorHarnessAxi.hpp \
    \
    jlm/hls/backend/rvsdg2rhls/add-buffers.hpp \
    jlm/hls/backend/rvsdg2rhls/add-forks.hpp \
    jlm/hls/backend/rvsdg2rhls/add-prints.hpp \
    jlm/hls/backend/rvsdg2rhls/add-sinks.hpp \
    jlm/hls/backend/rvsdg2rhls/alloca-conv.hpp \
    jlm/hls/backend/rvsdg2rhls/check-rhls.hpp \
    jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.hpp \
    jlm/hls/backend/rvsdg2rhls/decouple-mem-state.hpp \
    jlm/hls/backend/rvsdg2rhls/distribute-constants.hpp \
    jlm/hls/backend/rvsdg2rhls/GammaConversion.hpp \
    jlm/hls/backend/rvsdg2rhls/hls-function-util.hpp \
    jlm/hls/backend/rvsdg2rhls/instrument-ref.hpp \
    jlm/hls/backend/rvsdg2rhls/mem-conv.hpp \
    jlm/hls/backend/rvsdg2rhls/mem-queue.hpp \
    jlm/hls/backend/rvsdg2rhls/mem-sep.hpp \
    jlm/hls/backend/rvsdg2rhls/memstate-conv.hpp \
    jlm/hls/backend/rvsdg2rhls/merge-gamma.hpp \
    jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.hpp \
    jlm/hls/backend/rvsdg2rhls/rhls-dne.hpp \
    jlm/hls/backend/rvsdg2rhls/stream-conv.hpp \
    jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.hpp \
    jlm/hls/backend/rvsdg2rhls/ThetaConversion.hpp \
    jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.hpp \
    \
    jlm/hls/ir/hls.hpp \
    \
    jlm/hls/opt/cne.hpp \
    jlm/hls/opt/IOBarrierRemoval.hpp \
    jlm/hls/opt/IOStateElimination.hpp \
    \
    jlm/hls/util/view.hpp \
    \
    jlm/hls/HlsDotWriter.hpp \

$(eval $(call common_library,libhls))

tests/jlm/hls/run-libhls-tests_SOURCES = \
    tests/jlm/hls/backend/rvsdg2rhls/DeadNodeEliminationTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/DistributeConstantsTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/MemoryConverterTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/MemoryQueueTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/MemoryStateSplitConversionTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/RedundantBufferEliminationTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/SinkInsertionTests.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/test-loop-passthrough.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/TestFork.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/TestGamma.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/TestTheta.cpp \
    tests/jlm/hls/backend/rvsdg2rhls/UnusedStateRemovalTests.cpp \
    tests/jlm/hls/opt/IOBarrierRemovalTests.cpp \
    tests/jlm/hls/opt/IOStateEliminationTests.cpp \
    tests/jlm/hls/util/ViewTests.cpp \

tests/jlm/hls/run-libhls-tests_LIBS = libhls libllvm librvsdg libutil
tests/jlm/hls/run-libhls-tests_EXTRA_LDFLAGS = $(shell $(LLVMCONFIG) --ldflags --libs --system-libs)
$(eval $(call common_test,tests/jlm/hls/run-libhls-tests))
