# Copyright 2019 Nico Reißmann <nico.reissmann@gmail.com>
# See COPYING for terms of redistribution.

libhls_SOURCES = \
    jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.cpp \
    \
    jlm/hls/backend/rhls2firrtl/base-hls.cpp \
    jlm/hls/backend/rhls2firrtl/dot-hls.cpp \
    jlm/hls/backend/rhls2firrtl/json-hls.cpp \
    jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp \
    jlm/hls/backend/rhls2firrtl/verilator-harness-hls.cpp \
    \
    jlm/hls/backend/rvsdg2rhls/add-buffers.cpp \
    jlm/hls/backend/rvsdg2rhls/add-forks.cpp \
    jlm/hls/backend/rvsdg2rhls/add-prints.cpp \
    jlm/hls/backend/rvsdg2rhls/add-sinks.cpp \
    jlm/hls/backend/rvsdg2rhls/add-triggers.cpp \
    jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/check-rhls.cpp \
    jlm/hls/backend/rvsdg2rhls/dae-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.cpp \
    jlm/hls/backend/rvsdg2rhls/distribute-constants.cpp \
    jlm/hls/backend/rvsdg2rhls/GammaConversion.cpp \
    jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-queue.cpp \
    jlm/hls/backend/rvsdg2rhls/mem-sep.cpp \
    jlm/hls/backend/rvsdg2rhls/memstate-conv.cpp \
    jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp \
    jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp \
    jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp \
    jlm/hls/backend/rvsdg2rhls/rhls-dne.cpp \
    jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp \
    jlm/hls/backend/rvsdg2rhls/ThetaConversion.cpp \
    jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp \
    \
    jlm/hls/ir/hls.cpp \
    \
    jlm/hls/opt/cne.cpp \
    \
    jlm/hls/util/view.cpp \

libhls_HEADERS = \
	jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.hpp \
	\
	jlm/hls/backend/rhls2firrtl/base-hls.hpp \
	jlm/hls/backend/rhls2firrtl/dot-hls.hpp \
	jlm/hls/backend/rhls2firrtl/json-hls.hpp \
	jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp \
	jlm/hls/backend/rhls2firrtl/verilator-harness-hls.hpp \
	\
	jlm/hls/backend/rvsdg2rhls/add-buffers.hpp \
	jlm/hls/backend/rvsdg2rhls/add-forks.hpp \
	jlm/hls/backend/rvsdg2rhls/add-prints.hpp \
	jlm/hls/backend/rvsdg2rhls/add-sinks.hpp \
	jlm/hls/backend/rvsdg2rhls/add-triggers.hpp \
	jlm/hls/backend/rvsdg2rhls/alloca-conv.hpp \
	jlm/hls/backend/rvsdg2rhls/check-rhls.hpp \
	jlm/hls/backend/rvsdg2rhls/dae-conv.hpp \
	jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.hpp \
	jlm/hls/backend/rvsdg2rhls/distribute-constants.hpp \
	jlm/hls/backend/rvsdg2rhls/GammaConversion.hpp \
	jlm/hls/backend/rvsdg2rhls/instrument-ref.hpp \
	jlm/hls/backend/rvsdg2rhls/mem-conv.hpp \
	jlm/hls/backend/rvsdg2rhls/mem-queue.hpp \
	jlm/hls/backend/rvsdg2rhls/mem-sep.hpp \
	jlm/hls/backend/rvsdg2rhls/memstate-conv.hpp \
	jlm/hls/backend/rvsdg2rhls/merge-gamma.hpp \
	jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.hpp \
	jlm/hls/backend/rvsdg2rhls/remove-unused-state.hpp \
	jlm/hls/backend/rvsdg2rhls/rhls-dne.hpp \
	jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.hpp \
	jlm/hls/backend/rvsdg2rhls/ThetaConversion.hpp \
	jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.hpp \
	\
	jlm/hls/ir/hls.hpp \
	\
	jlm/hls/opt/cne.hpp \
	\
	jlm/hls/util/view.hpp \

libhls_TESTS += \
	tests/jlm/hls/backend/rvsdg2rhls/DeadNodeEliminationTests \
	tests/jlm/hls/backend/rvsdg2rhls/MemoryConverterTests \
	tests/jlm/hls/backend/rvsdg2rhls/MemoryQueueTests \
	tests/jlm/hls/backend/rvsdg2rhls/TestFork \
	tests/jlm/hls/backend/rvsdg2rhls/TestGamma \
	tests/jlm/hls/backend/rvsdg2rhls/TestTheta \
	tests/jlm/hls/backend/rvsdg2rhls/UnusedStateRemovalTests \
	tests/jlm/hls/backend/rvsdg2rhls/test-loop-passthrough \
	tests/jlm/hls/util/TestView \

libhls_TEST_LIBS += \
	libjlmtest \
	libhls \
	libllvm \
	librvsdg \
	libutil \

libhls_TEST_EXTRA_LDFLAGS = $(shell $(LLVMCONFIG) --ldflags --libs --system-libs)

$(eval $(call common_library,libhls))
