name: ClangFormat

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  CheckFormat:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Install clang format"
        uses: ./.github/actions/InstallPackages
        with:
          install-llvm: true # Needed to configure jlm
          install-clang-format: true
      - name: "Configure jlm with HLS and MLIR enabled"
        run: ./configure.sh --enable-mlir --enable-hls
      - name: "Check format"
        run: make format-dry-run
