name: Doxygen

on:
  pull_request:
    branches: [ master ]

jobs:
  GenerateDocumentation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Install doxygen"
        uses: ./.github/actions/InstallPackages
        with:
          install-doxygen: true
      - name: "Build documentation"
        uses: ./.github/actions/BuildJlm
        with:
          make-target: docs