name: Doxygen

on:
  pull_request:
    branches: [ master ]

jobs:
  GenerateDocumentation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install graphviz doxygen llvm-16-dev
      - name: Configure jlm
        run: ./configure.sh
      - name: Generate documentation
        run: make docs