name: Doxygen

on:
  pull_request:
    branches: [ master ]

jobs:
  GenerateDocumentation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install doxygen and graphviz
        run: sudo apt-get install graphviz doxygen
      - name: "Build jlm"
        uses: ./.github/actions/BuildJlm
        with:
          make-target: docs